// @vitest-environment node
import { PGlite } from '@electric-sql/pglite';
import { drizzle } from 'drizzle-orm/pglite';
import { afterEach, describe, expect, it } from 'vitest';

import migrations from './migrations.json';

const {
  MESSAGE_ORDER_BACKFILL_SQL,
  MESSAGE_ORDER_FINALIZE_SQL,
  MESSAGE_ORDER_SCHEMA_SQL,
} = require('../../../../scripts/migrateServerDB/ensureMessageOrder.cjs');
const {
  CHAT_GROUP_MEMBERSHIP_OWNERSHIP_SQL,
} = require('../../../../scripts/migrateServerDB/ensureChatGroupMembershipOwnership.cjs');

const MIGRATION_0040_TIMESTAMP = 1_761_563_458_595;
const MIGRATION_0041_TIMESTAMP = 1_741_622_400_000;
const MIGRATION_0044_TIMESTAMP = 1_745_908_800_000;
const MIGRATION_0045_TIMESTAMP = 1_784_468_303_298;
const MIGRATION_0046_TIMESTAMP = 1_784_473_972_091;
const MIGRATION_0048_TIMESTAMP = 1_784_687_753_515;

describe('client migration upgrades', () => {
  let client: PGlite | undefined;

  afterEach(async () => {
    await client?.close();
    client = undefined;
  });

  it('repairs schema changes skipped after the 0040 timestamp high-water mark', async () => {
    client = new PGlite();
    await client.exec(`
      CREATE TABLE "users" (
        "id" text PRIMARY KEY NOT NULL
      );
      INSERT INTO "users" ("id") VALUES ('migration-user');

      CREATE TABLE "mcp_oauth_tokens" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "user_id" text NOT NULL REFERENCES "public"."users"("id") ON DELETE CASCADE,
        "plugin_identifier" varchar(256) NOT NULL,
        "access_token" text NOT NULL,
        "refresh_token" text,
        "token_type" varchar(64) DEFAULT 'Bearer',
        "expires_at" timestamp with time zone,
        "scope" text,
        "client_id" varchar(256) NOT NULL,
        "server_metadata" jsonb,
        "accessed_at" timestamp with time zone DEFAULT now() NOT NULL,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL,
        "updated_at" timestamp with time zone DEFAULT now() NOT NULL
      );

      CREATE TABLE "agents" (
        "id" text PRIMARY KEY NOT NULL
      );

      CREATE TABLE "messages" (
        "id" text PRIMARY KEY NOT NULL,
        "parent_id" text,
        "topic_id" text,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL
      );

      CREATE TABLE "topics" (
        "id" text PRIMARY KEY NOT NULL,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL,
        "updated_at" timestamp with time zone DEFAULT now() NOT NULL
      );

      INSERT INTO "topics" ("id", "created_at", "updated_at")
      VALUES ('historical-topic', '2024-01-01T00:00:00.000Z', '2024-01-02T00:00:00.000Z');

      INSERT INTO "messages" ("id", "topic_id", "created_at")
      VALUES ('historical-topic-message', 'historical-topic', '2024-01-03T00:00:00.000Z');

      CREATE INDEX "messages_created_at_idx" ON "messages" ("created_at");

      INSERT INTO "messages" ("id", "parent_id", "created_at")
      VALUES
        ('turn-z', NULL, '2024-01-01T00:00:00.000Z'),
        ('reply-z', 'turn-z', '2024-01-01T00:00:00.000Z'),
        ('turn-a', NULL, '2024-01-01T00:00:00.000Z'),
        ('reply-a', 'turn-a', '2024-01-01T00:00:00.000Z');

      CREATE SCHEMA "drizzle";
      CREATE TABLE "drizzle"."__drizzle_migrations" (
        "id" serial PRIMARY KEY,
        "hash" text NOT NULL,
        "created_at" bigint
      );

      INSERT INTO "drizzle"."__drizzle_migrations" ("hash", "created_at")
      VALUES ('0040-high-water-mark', ${MIGRATION_0040_TIMESTAMP});
    `);

    const database = drizzle({ client });

    await database.dialect.migrate(migrations, database.session, {});

    const migrationRows = await client.query<{ created_at: string }>(`
      SELECT "created_at"
      FROM "drizzle"."__drizzle_migrations"
      ORDER BY "created_at";
    `);
    const appliedMigrationTimestamps = migrationRows.rows.map(({ created_at }) =>
      Number(created_at),
    );

    expect(appliedMigrationTimestamps).toContain(MIGRATION_0040_TIMESTAMP);
    expect(appliedMigrationTimestamps).not.toContain(MIGRATION_0041_TIMESTAMP);
    expect(appliedMigrationTimestamps).not.toContain(MIGRATION_0044_TIMESTAMP);
    expect(appliedMigrationTimestamps).toContain(MIGRATION_0045_TIMESTAMP);
    expect(appliedMigrationTimestamps).toContain(MIGRATION_0046_TIMESTAMP);
    expect(appliedMigrationTimestamps).toContain(MIGRATION_0048_TIMESTAMP);

    const orderedMessages = await client.query<{ id: string }>(`
      SELECT "id"
      FROM "messages"
      ORDER BY "created_at", "message_order";
    `);
    expect(orderedMessages.rows.map(({ id }) => id)).toEqual([
      'turn-z',
      'reply-z',
      'turn-a',
      'reply-a',
      'historical-topic-message',
    ]);

    const repairedSchema = await client.query<{
      assistant_memory_exists: boolean;
      mcp_oauth_tokens_exists: boolean;
      picbed_images_exists: boolean;
    }>(`
      SELECT
        EXISTS (
          SELECT 1
          FROM information_schema.columns
          WHERE table_schema = 'public'
            AND table_name = 'agents'
            AND column_name = 'assistant_memory'
        ) AS assistant_memory_exists,
        to_regclass('public.mcp_oauth_tokens') IS NOT NULL AS mcp_oauth_tokens_exists,
        to_regclass('public.picbed_images') IS NOT NULL AS picbed_images_exists;
    `);

    expect(repairedSchema.rows[0]).toEqual({
      assistant_memory_exists: true,
      mcp_oauth_tokens_exists: true,
      picbed_images_exists: true,
    });

    const repairedTopic = await client.query<{
      last_activity_at: Date;
      topic_id: string;
    }>(`
      SELECT "id" AS topic_id, "last_activity_at"
      FROM "topics"
      WHERE "id" = 'historical-topic';
    `);

    expect(repairedTopic.rows).toEqual([
      {
        last_activity_at: new Date('2024-01-03T00:00:00.000Z'),
        topic_id: 'historical-topic',
      },
    ]);

    const repairedUser = await client.query<{ conversation_version: number }>(`
      SELECT "conversation_version"
      FROM "users"
      WHERE "id" = 'migration-user';
    `);
    expect(repairedUser.rows).toEqual([{ conversation_version: 0 }]);

    const mcpOAuthForeignKeys = await client.query<{ constraint_name: string }>(`
      SELECT conname AS constraint_name
      FROM pg_constraint
      WHERE conrelid = 'public.mcp_oauth_tokens'::regclass
        AND contype = 'f';
    `);

    expect(mcpOAuthForeignKeys.rows).toEqual([
      { constraint_name: 'mcp_oauth_tokens_user_id_users_id_fk' },
    ]);
  });

  it('re-ranks a partially populated message order before the child', async () => {
    client = new PGlite();
    await client.exec(`
      CREATE TABLE "messages" (
        "id" text PRIMARY KEY NOT NULL,
        "parent_id" text,
        "created_at" timestamp with time zone NOT NULL,
        "message_order" bigint
      );

      CREATE SEQUENCE "messages_message_order_seq";

      INSERT INTO "messages" ("id", "parent_id", "created_at", "message_order")
      VALUES
        ('child-a', 'parent-z', '2024-01-01T00:00:00.000Z', 1),
        ('parent-z', NULL, '2024-01-01T00:00:00.000Z', NULL);
    `);

    await client.exec(MESSAGE_ORDER_SCHEMA_SQL);
    await client.exec(MESSAGE_ORDER_BACKFILL_SQL);
    await client.exec(MESSAGE_ORDER_FINALIZE_SQL);

    const orderedMessages = await client.query<{
      id: string;
      message_order: number;
    }>(`
      SELECT "id", "message_order"
      FROM "messages"
      ORDER BY "message_order";
    `);

    expect(orderedMessages.rows).toEqual([
      { id: 'parent-z', message_order: 1 },
      { id: 'child-a', message_order: 2 },
    ]);

    const nextMessageOrder = await client.query<{ next_order: number }>(`
      SELECT nextval('messages_message_order_seq') AS next_order;
    `);

    expect(nextMessageOrder.rows[0]?.next_order).toBe(3);
  });

  it('converges drifted group memberships and cascading ownership constraints', async () => {
    client = new PGlite();
    await client.exec(`
      CREATE TABLE "users" (
        "id" text PRIMARY KEY NOT NULL
      );
      CREATE TABLE "agents" (
        "id" text PRIMARY KEY NOT NULL,
        "user_id" text NOT NULL
      );
      CREATE TABLE "chat_groups" (
        "id" text PRIMARY KEY NOT NULL,
        "user_id" text NOT NULL
      );
      CREATE TABLE "chat_groups_agents" (
        "chat_group_id" text NOT NULL,
        "agent_id" text NOT NULL,
        "user_id" text NOT NULL,
        PRIMARY KEY ("chat_group_id", "agent_id")
      );

      INSERT INTO "users" ("id")
      VALUES ('owner-a'), ('owner-b'), ('stale-owner');
      INSERT INTO "agents" ("id", "user_id")
      VALUES
        ('owner-a-agent', 'owner-a'),
        ('owner-b-agent', 'owner-b'),
        ('ghost-agent', 'ghost-owner'),
        ('agent-delete-agent', 'owner-a'),
        ('group-delete-agent', 'owner-a'),
        ('user-delete-agent', 'owner-b');
      INSERT INTO "chat_groups" ("id", "user_id")
      VALUES
        ('same-owner-group', 'owner-a'),
        ('cross-owner-group', 'owner-a'),
        ('ghost-group', 'ghost-owner'),
        ('agent-delete-group', 'owner-a'),
        ('group-delete-group', 'owner-a'),
        ('user-delete-group', 'owner-b');
      INSERT INTO "chat_groups_agents" ("chat_group_id", "agent_id", "user_id")
      VALUES
        ('same-owner-group', 'owner-a-agent', 'stale-owner'),
        ('cross-owner-group', 'owner-b-agent', 'owner-a'),
        ('missing-group', 'owner-a-agent', 'owner-a'),
        ('same-owner-group', 'missing-agent', 'owner-a'),
        ('ghost-group', 'ghost-agent', 'ghost-owner'),
        ('agent-delete-group', 'agent-delete-agent', 'owner-a'),
        ('group-delete-group', 'group-delete-agent', 'owner-a'),
        ('user-delete-group', 'user-delete-agent', 'owner-b');

      CREATE UNIQUE INDEX "agents_owner_reference_unique"
        ON "agents" ("id", "user_id");
      CREATE UNIQUE INDEX "chat_groups_owner_reference_unique"
        ON "chat_groups" ("id", "user_id");
      CREATE UNIQUE INDEX "agents_id_user_id_unique"
        ON "agents" ("user_id", "id");
      CREATE UNIQUE INDEX "chat_groups_id_user_id_unique"
        ON "chat_groups" ("user_id", "id");

      ALTER TABLE "chat_groups_agents"
        ADD CONSTRAINT "chat_groups_agents_chat_group_id_chat_groups_id_fk"
        FOREIGN KEY ("chat_group_id")
        REFERENCES "chat_groups"("id")
        ON DELETE NO ACTION
        NOT VALID;
      ALTER TABLE "chat_groups_agents"
        ADD CONSTRAINT "chat_groups_agents_agent_id_agents_id_fk"
        FOREIGN KEY ("agent_id")
        REFERENCES "agents"("id")
        ON DELETE NO ACTION
        NOT VALID;
      ALTER TABLE "chat_groups_agents"
        ADD CONSTRAINT "chat_groups_agents_user_id_users_id_fk"
        FOREIGN KEY ("user_id")
        REFERENCES "users"("id")
        ON DELETE NO ACTION
        NOT VALID;
      ALTER TABLE "chat_groups_agents"
        ADD CONSTRAINT "chat_groups_agents_agent_id_user_id_agents_id_user_id_fk"
        FOREIGN KEY ("agent_id", "user_id")
        REFERENCES "agents"("id", "user_id")
        ON DELETE NO ACTION
        NOT VALID;
      ALTER TABLE "chat_groups_agents"
        ADD CONSTRAINT "chat_groups_agents_group_id_user_id_chat_groups_id_user_id_fk"
        FOREIGN KEY ("chat_group_id", "user_id")
        REFERENCES "chat_groups"("id", "user_id")
        ON DELETE NO ACTION
        NOT VALID;
    `);

    await client.exec(CHAT_GROUP_MEMBERSHIP_OWNERSHIP_SQL);
    await client.exec(CHAT_GROUP_MEMBERSHIP_OWNERSHIP_SQL);

    const repairedMemberships = await client.query<{
      agent_id: string;
      chat_group_id: string;
      user_id: string;
    }>(`
      SELECT "chat_group_id", "agent_id", "user_id"
      FROM "chat_groups_agents"
      ORDER BY "chat_group_id", "agent_id";
    `);
    expect(repairedMemberships.rows).toEqual([
      {
        agent_id: 'agent-delete-agent',
        chat_group_id: 'agent-delete-group',
        user_id: 'owner-a',
      },
      {
        agent_id: 'group-delete-agent',
        chat_group_id: 'group-delete-group',
        user_id: 'owner-a',
      },
      {
        agent_id: 'owner-a-agent',
        chat_group_id: 'same-owner-group',
        user_id: 'owner-a',
      },
      {
        agent_id: 'user-delete-agent',
        chat_group_id: 'user-delete-group',
        user_id: 'owner-b',
      },
    ]);

    const ownershipConstraints = await client.query<{
      constraint_name: string;
      delete_action: string;
      is_validated: boolean;
      update_action: string;
    }>(`
      SELECT
        conname AS constraint_name,
        confdeltype AS delete_action,
        confupdtype AS update_action,
        convalidated AS is_validated
      FROM pg_constraint
      WHERE conrelid = 'public.chat_groups_agents'::regclass
        AND conname IN (
          'chat_groups_agents_chat_group_id_chat_groups_id_fk',
          'chat_groups_agents_agent_id_agents_id_fk',
          'chat_groups_agents_user_id_users_id_fk',
          'chat_groups_agents_agent_id_user_id_agents_id_user_id_fk',
          'chat_groups_agents_group_id_user_id_chat_groups_id_user_id_fk'
        )
      ORDER BY conname;
    `);
    expect(ownershipConstraints.rows).toEqual([
      {
        constraint_name: 'chat_groups_agents_agent_id_agents_id_fk',
        delete_action: 'c',
        is_validated: true,
        update_action: 'a',
      },
      {
        constraint_name: 'chat_groups_agents_agent_id_user_id_agents_id_user_id_fk',
        delete_action: 'c',
        is_validated: true,
        update_action: 'a',
      },
      {
        constraint_name: 'chat_groups_agents_chat_group_id_chat_groups_id_fk',
        delete_action: 'c',
        is_validated: true,
        update_action: 'a',
      },
      {
        constraint_name: 'chat_groups_agents_group_id_user_id_chat_groups_id_user_id_fk',
        delete_action: 'c',
        is_validated: true,
        update_action: 'a',
      },
      {
        constraint_name: 'chat_groups_agents_user_id_users_id_fk',
        delete_action: 'c',
        is_validated: true,
        update_action: 'a',
      },
    ]);

    const ownershipIndexes = await client.query<{
      column_names: string;
      index_name: string;
      is_unique: boolean;
    }>(`
      SELECT
        index_class.relname AS index_name,
        index_definition.indisunique AS is_unique,
        string_agg(column_definition.attname, ',' ORDER BY key_columns.ordinality) AS column_names
      FROM pg_index AS index_definition
      JOIN pg_class AS index_class ON index_class.oid = index_definition.indexrelid
      CROSS JOIN LATERAL unnest(index_definition.indkey)
        WITH ORDINALITY AS key_columns(attribute_number, ordinality)
      JOIN pg_attribute AS column_definition
        ON column_definition.attrelid = index_definition.indrelid
        AND column_definition.attnum = key_columns.attribute_number
      WHERE index_class.relname IN (
        'agents_id_user_id_unique',
        'chat_groups_id_user_id_unique'
      )
      GROUP BY index_class.relname, index_definition.indisunique
      ORDER BY index_class.relname;
    `);
    expect(ownershipIndexes.rows).toEqual([
      {
        column_names: 'id,user_id',
        index_name: 'agents_id_user_id_unique',
        is_unique: true,
      },
      {
        column_names: 'id,user_id',
        index_name: 'chat_groups_id_user_id_unique',
        is_unique: true,
      },
    ]);

    await expect(
      client.exec(`
        INSERT INTO "chat_groups_agents" ("chat_group_id", "agent_id", "user_id")
        VALUES ('same-owner-group', 'owner-b-agent', 'owner-a');
      `),
    ).rejects.toThrow();
    await expect(
      client.exec(`
        INSERT INTO "chat_groups_agents" ("chat_group_id", "agent_id", "user_id")
        VALUES ('same-owner-group', 'owner-b-agent', 'owner-b');
      `),
    ).rejects.toThrow();

    await client.exec(`
      DELETE FROM "agents" WHERE "id" = 'agent-delete-agent';
      DELETE FROM "chat_groups" WHERE "id" = 'group-delete-group';
      DELETE FROM "users" WHERE "id" = 'owner-b';
    `);

    const membershipsAfterParentDeletes = await client.query<{
      agent_id: string;
      chat_group_id: string;
    }>(`
      SELECT "chat_group_id", "agent_id"
      FROM "chat_groups_agents"
      ORDER BY "chat_group_id", "agent_id";
    `);
    expect(membershipsAfterParentDeletes.rows).toEqual([
      {
        agent_id: 'owner-a-agent',
        chat_group_id: 'same-owner-group',
      },
    ]);
  });
});
