/**
 * Idempotent repair for per-user SuperGrok / xAI OAuth tokens.
 * Safe to run after every migration (matches migration 0060).
 */
const XAI_OAUTH_TOKENS_SQL = `
CREATE TABLE IF NOT EXISTS "xai_oauth_tokens" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "xai_oauth_tokens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
  "user_id" text NOT NULL,
  "access_token" text NOT NULL,
  "refresh_token" text NOT NULL,
  "expires_at" timestamp with time zone NOT NULL,
  "email" varchar(256),
  "plan" varchar(64),
  "token_endpoint" varchar(512),
  "client_id" varchar(256) NOT NULL,
  "refresh_lock_id" varchar(256),
  "refresh_lock_until" timestamp with time zone,
  "accessed_at" timestamp with time zone DEFAULT now() NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

DO $$ BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'xai_oauth_tokens_user_id_unique'
      AND conrelid = 'public.xai_oauth_tokens'::regclass
  ) OR to_regclass('public.xai_oauth_tokens_user_id_unique') IS NOT NULL THEN
    NULL;
  ELSE
    ALTER TABLE "xai_oauth_tokens"
      ADD CONSTRAINT "xai_oauth_tokens_user_id_unique" UNIQUE ("user_id");
  END IF;
EXCEPTION
  WHEN duplicate_object THEN null;
  WHEN duplicate_table THEN null;
  WHEN unique_violation THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "xai_oauth_tokens"
    ADD CONSTRAINT "xai_oauth_tokens_user_id_users_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

ALTER TABLE "xai_oauth_tokens"
  ADD COLUMN IF NOT EXISTS "refresh_lock_id" varchar(256);
ALTER TABLE "xai_oauth_tokens"
  ADD COLUMN IF NOT EXISTS "refresh_lock_until" timestamp with time zone;
ALTER TABLE "xai_oauth_tokens"
  ADD COLUMN IF NOT EXISTS "email" varchar(256);
ALTER TABLE "xai_oauth_tokens"
  ADD COLUMN IF NOT EXISTS "plan" varchar(64);
ALTER TABLE "xai_oauth_tokens"
  ADD COLUMN IF NOT EXISTS "token_endpoint" varchar(512);
`;

const ensureXaiOAuthTokensTable = async (client) => {
  await client.query(XAI_OAUTH_TOKENS_SQL);
};

module.exports = {
  XAI_OAUTH_TOKENS_SQL,
  ensureXaiOAuthTokensTable,
};
