/**
 * Idempotent repair for per-user ChatGPT / Codex subscription tokens.
 * Safe to run after every migration (matches migration 0058).
 */
const OPENAI_CODEX_OAUTH_TOKENS_SQL = `
CREATE TABLE IF NOT EXISTS "openai_codex_oauth_tokens" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "openai_codex_oauth_tokens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
  "user_id" text NOT NULL,
  "access_token" text NOT NULL,
  "refresh_token" text NOT NULL,
  "expires_at" timestamp with time zone NOT NULL,
  "account_id" varchar(256) NOT NULL,
  "email" varchar(256),
  "chatgpt_plan_type" varchar(64),
  "client_id" varchar(256) NOT NULL,
  "accessed_at" timestamp with time zone DEFAULT now() NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

DO $$ BEGIN
  ALTER TABLE "openai_codex_oauth_tokens"
    ADD CONSTRAINT "openai_codex_oauth_tokens_user_id_unique" UNIQUE ("user_id");
EXCEPTION
  WHEN duplicate_object THEN null;
  WHEN unique_violation THEN null;
END $$;

ALTER TABLE "openai_codex_oauth_tokens"
  DROP CONSTRAINT IF EXISTS "openai_codex_oauth_tokens_user_id_fkey";

DO $$ BEGIN
  ALTER TABLE "openai_codex_oauth_tokens"
    RENAME CONSTRAINT "openai_codex_oauth_tokens_user_id_fkey"
    TO "openai_codex_oauth_tokens_user_id_users_id_fk";
EXCEPTION
  WHEN undefined_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "openai_codex_oauth_tokens"
    ADD CONSTRAINT "openai_codex_oauth_tokens_user_id_users_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;
`;

const ensureOpenAICodexOAuthTokensTable = async (client) => {
  await client.query(OPENAI_CODEX_OAUTH_TOKENS_SQL);
};

module.exports = {
  OPENAI_CODEX_OAUTH_TOKENS_SQL,
  ensureOpenAICodexOAuthTokensTable,
};
