/**
 * Idempotent repair: some deployments reported missing "mcp_oauth_tokens"
 * after DB resets when the migration journal and image drifted or migrator skipped a step.
 * Safe to run after every migration (matches 0044_add_mcp_oauth_tokens.sql).
 */
const MCP_OAUTH_TOKENS_SQL = `CREATE TABLE IF NOT EXISTS "mcp_oauth_tokens" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" text NOT NULL,
  "plugin_identifier" varchar(256) NOT NULL,
  "access_token" text NOT NULL,
  "refresh_token" text,
  "token_type" varchar(64) DEFAULT 'Bearer',
  "expires_at" timestamp with time zone,
  "scope" text,
  "client_id" varchar(256) NOT NULL,
  "server_metadata" jsonb,
  "accessed_at" timestamp with time zone DEFAULT now() NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

DO $$ BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'mcp_oauth_tokens_user_id_users_id_fk'
      AND conrelid = 'public.mcp_oauth_tokens'::regclass
  ) THEN
    ALTER TABLE "mcp_oauth_tokens"
      DROP CONSTRAINT IF EXISTS "mcp_oauth_tokens_user_id_fkey";
  ELSIF EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'mcp_oauth_tokens_user_id_fkey'
      AND conrelid = 'public.mcp_oauth_tokens'::regclass
  ) THEN
    ALTER TABLE "mcp_oauth_tokens"
      RENAME CONSTRAINT "mcp_oauth_tokens_user_id_fkey"
      TO "mcp_oauth_tokens_user_id_users_id_fk";
  ELSE
    ALTER TABLE "mcp_oauth_tokens"
      ADD CONSTRAINT "mcp_oauth_tokens_user_id_users_id_fk"
      FOREIGN KEY ("user_id")
      REFERENCES "public"."users"("id")
      ON DELETE cascade
      ON UPDATE no action;
  END IF;
END $$;`;

/** @param {{ query: (sql: string) => Promise<unknown> }} client node-pg Pool or compatible */
const ensureMcpOAuthTokensTable = async (client) => {
  await client.query(MCP_OAUTH_TOKENS_SQL);
};

module.exports = { MCP_OAUTH_TOKENS_SQL, ensureMcpOAuthTokensTable };
