// @vitest-environment node
import { PGlite } from '@electric-sql/pglite';
import { afterEach, describe, expect, it } from 'vitest';

const { MCP_OAUTH_TOKENS_SQL } = require('./ensureMcpOAuthTokens.cjs');

const createUsersTable = async (client: PGlite): Promise<void> => {
  await client.exec(`
    CREATE TABLE "users" (
      "id" text PRIMARY KEY NOT NULL
    );
  `);
};

const createMcpOAuthTokensTable = async (client: PGlite): Promise<void> => {
  await client.exec(`
    CREATE TABLE "mcp_oauth_tokens" (
      "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      "user_id" text NOT NULL,
      "plugin_identifier" varchar(256) NOT NULL,
      "access_token" text NOT NULL,
      "refresh_token" text,
      "token_type" varchar(64) DEFAULT 'Bearer',
      "expires_at" timestamp with time zone,
      "scope" text,
      "client_id" varchar(256) NOT NULL,
      "server_metadata" jsonb,
      "accessed_at" timestamp with time zone DEFAULT now() NOT NULL,
      "created_at" timestamp with time zone DEFAULT now() NOT NULL,
      "updated_at" timestamp with time zone DEFAULT now() NOT NULL
    );
  `);
};

const getForeignKeyNames = async (client: PGlite): Promise<string[]> => {
  const result = await client.query<{ conname: string }>(`
    SELECT conname
    FROM pg_constraint
    WHERE conrelid = 'public.mcp_oauth_tokens'::regclass
      AND contype = 'f'
    ORDER BY conname;
  `);

  return result.rows.map(({ conname }) => conname);
};

describe('MCP OAuth token table repair', () => {
  let client: PGlite | undefined;

  afterEach(async () => {
    await client?.close();
    client = undefined;
  });

  it('renames the legacy auto-named foreign key to the canonical name', async () => {
    client = new PGlite();
    await createUsersTable(client);
    await createMcpOAuthTokensTable(client);
    await client.exec(`
      ALTER TABLE "mcp_oauth_tokens"
        ADD CONSTRAINT "mcp_oauth_tokens_user_id_fkey"
        FOREIGN KEY ("user_id")
        REFERENCES "public"."users"("id")
        ON DELETE cascade;
    `);

    await client.exec(MCP_OAUTH_TOKENS_SQL);

    await expect(getForeignKeyNames(client)).resolves.toEqual([
      'mcp_oauth_tokens_user_id_users_id_fk',
    ]);
  });

  it('drops a legacy duplicate when the canonical foreign key already exists', async () => {
    client = new PGlite();
    await createUsersTable(client);
    await createMcpOAuthTokensTable(client);
    await client.exec(`
      ALTER TABLE "mcp_oauth_tokens"
        ADD CONSTRAINT "mcp_oauth_tokens_user_id_fkey"
        FOREIGN KEY ("user_id")
        REFERENCES "public"."users"("id")
        ON DELETE cascade;
      ALTER TABLE "mcp_oauth_tokens"
        ADD CONSTRAINT "mcp_oauth_tokens_user_id_users_id_fk"
        FOREIGN KEY ("user_id")
        REFERENCES "public"."users"("id")
        ON DELETE cascade;
    `);

    await client.exec(MCP_OAUTH_TOKENS_SQL);

    await expect(getForeignKeyNames(client)).resolves.toEqual([
      'mcp_oauth_tokens_user_id_users_id_fk',
    ]);
  });
});
